"""
Module: talos.findings.model

Purpose:
    Data-model constants and type definitions for the Findings subsystem.

    Defines:
        FINDING_STATUS_*     — lifecycle states for a finding.
        EVIDENCE_TYPE_*      — canonical evidence type labels.
        TIMELINE_ACTOR_*     — who created a timeline event.
        ATTACK_TYPE_*        — short attack-module labels stored on findings.
        VERDICT_TRIGGERS     — which verdict strings create a finding per attack.

Dependencies: None (pure constants — no imports required).
Data flow: Consumed by talos.findings.db, talos.findings.creator, talos.findings.cli.
Side effects: None.
"""

# ------------------------------------------------------------------ #
# Finding status constants                                             #
# ------------------------------------------------------------------ #

FINDING_STATUS_TRIAGING  = "TRIAGING"
"""Newly created; awaiting analyst review."""

FINDING_STATUS_CONFIRMED = "CONFIRMED"
"""Analyst confirmed this is a real vulnerability."""

FINDING_STATUS_REJECTED  = "REJECTED"
"""Analyst determined this is a false positive."""

FINDING_STATUS_DUPLICATE = "DUPLICATE"
"""Analyst marked this as a duplicate of another finding."""

FINDING_STATUSES: tuple[str, ...] = (
    FINDING_STATUS_TRIAGING,
    FINDING_STATUS_CONFIRMED,
    FINDING_STATUS_REJECTED,
    FINDING_STATUS_DUPLICATE,
)

# ------------------------------------------------------------------ #
# Finding relationship constants                                       #
# ------------------------------------------------------------------ #
# PRIMARY / LINKED control how findings are grouped for display.
# They are independent of lifecycle status (TRIAGING / CONFIRMED / …)
# and independent of the DUPLICATE status (a LINKED finding may also
# be marked DUPLICATE).
#
# Rules:
#   - PRIMARY findings have parent_finding_id = NULL
#   - LINKED findings must reference a PRIMARY parent
#   - Linked-to-linked (trees deeper than 1) is not allowed
#   - At most one PRIMARY per cluster_key (DB partial unique index)

RELATION_TYPE_PRIMARY = "PRIMARY"
"""Main finding for a vulnerability cluster."""

RELATION_TYPE_LINKED = "LINKED"
"""Successful attack result belonging to an existing PRIMARY cluster."""

RELATION_TYPES: tuple[str, ...] = (
    RELATION_TYPE_PRIMARY,
    RELATION_TYPE_LINKED,
)

# ------------------------------------------------------------------ #
# Evidence type constants                                              #
# ------------------------------------------------------------------ #

EVIDENCE_TYPE_ORIGINAL_FLOW          = "original_flow"
"""The original captured flow that was attacked."""

EVIDENCE_TYPE_REPLAY_FLOW            = "replay_flow"
"""The attack replay flow generated by the engine."""

EVIDENCE_TYPE_DIFF                   = "diff"
"""Replay diff result (SAME / DIFFERENT / ERROR)."""

EVIDENCE_TYPE_SCHEDULER_JOB         = "scheduler_job"
"""The scheduler job that triggered the attack."""

EVIDENCE_TYPE_ENDPOINT               = "endpoint"
"""The endpoint that was targeted."""

EVIDENCE_TYPE_DECISION_FILTER_RESULT = "decision_filter_result"
"""Decision filter match result (for BAC attacks)."""

EVIDENCE_TYPE_ANALYST_NOTE           = "analyst_note"
"""Free-form note added by an analyst."""

EVIDENCE_TYPE_ATTACKER_ROLE          = "attacker_role"
"""The attacker role used in a BAC attack."""

EVIDENCE_TYPE_TARGET_ROLE            = "target_role"
"""The target role used in a BAC attack."""

EVIDENCE_TYPE_AUTH_TEST_RESULT       = "auth_test_result"
"""Auth-bypass test result row reference."""

EVIDENCE_TYPE_BAC_RESULT             = "bac_result"
"""BAC attack result row reference."""

EVIDENCE_TYPE_UNAUTH_RESULT           = "unauth_result"
"""Unauthenticated-execution attack result row reference."""

EVIDENCE_TYPE_AUTH_SESSION_RESULT     = "auth_session_result"
"""Authentication & Session Testing result row reference."""

EVIDENCE_TYPE_CORS_RESULT             = "cors_result"
"""CORS misconfiguration probe result row reference."""

EVIDENCE_TYPE_SQLI_RESULT             = "sqli_result"
"""SQL injection probe result row reference."""

EVIDENCE_TYPE_PATH_TRAVERSAL_RESULT   = "path_traversal_result"
"""Path traversal / LFI probe result row reference."""

EVIDENCE_TYPE_SSRF_RESULT             = "ssrf_result"
"""SSRF probe result row reference."""

EVIDENCE_TYPE_OPEN_REDIRECT_RESULT    = "open_redirect_result"
"""Open-redirect probe result row reference."""

EVIDENCE_TYPE_SMUGGLE_RESULT          = "smuggle_result"
"""HTTP request smuggling probe result row reference."""

EVIDENCE_TYPE_MODULE                  = "module"
"""The application module (feature area) the target endpoint belongs to."""

EVIDENCE_TYPE_ROLE                    = "role"
"""The role that captured/owns the flow under test."""

EVIDENCE_TYPE_SOURCE_DOCUMENT         = "source_document"
"""Passive scan: source_documents row (body_hash identity)."""

EVIDENCE_TYPE_SOURCE_OCCURRENCE       = "source_occurrence"
"""Passive scan: source_occurrences row (URL/flow sighting)."""

EVIDENCE_TYPE_PASSIVE_DETECTION       = "passive_detection"
"""Passive scan: passive_detections row (scored secret observation)."""

EVIDENCE_TYPE_INTRUDER_RESULT         = "intruder_result"
"""Intruder: intruder_results row (matched / interesting attempt)."""

# ------------------------------------------------------------------ #
# Timeline actor constants                                             #
# ------------------------------------------------------------------ #

TIMELINE_ACTOR_SYSTEM  = "system"
"""Event recorded automatically by Talos."""

TIMELINE_ACTOR_ANALYST = "analyst"
"""Event recorded due to analyst action."""

# ------------------------------------------------------------------ #
# Verdict-to-finding trigger map                                       #
# Maps (attack_module_label → frozenset of verdict strings that
# trigger finding creation).  Any verdict NOT in the set is silent.
# ------------------------------------------------------------------ #

VERDICT_TRIGGERS: dict[str, frozenset[str]] = {
    "bac":          frozenset({"POSSIBLE_BAC"}),
    "auth_test":    frozenset({"BYPASS"}),
    "unauth":       frozenset({"BYPASS"}),
    "auth_session": frozenset({"WEAK_VALIDATION"}),
    "cors":         frozenset({"CORS_MISCONFIG"}),
    "sqli":            frozenset({"SQLI"}),
    "smuggle":         frozenset({"SMUGGLE"}),
    "path_traversal":  frozenset({"PATH_TRAVERSAL"}),
    "ssrf":            frozenset({"SSRF"}),
    "open_redirect":   frozenset({"OPEN_REDIRECT"}),
}

# ------------------------------------------------------------------ #
# Human-readable labels                                                #
# ------------------------------------------------------------------ #

ATTACK_DISPLAY: dict[str, str] = {
    "bac":            "Broken Access Control",
    "auth_test":      "Authentication Bypass",
    "unauth":         "Unauthenticated Execution",
    "auth_session":   "Authentication & Session Testing",
    "cors":           "CORS Misconfiguration",
    "sqli":            "SQL Injection",
    "smuggle":         "HTTP Request Smuggling",
    "path_traversal":  "Path Traversal / LFI",
    "ssrf":            "SSRF",
    "open_redirect":   "Open Redirect",
    "passive_secret": "Client-Side Secret Exposure",
    "intruder":       "Intruder Match",
    "ai_draft":       "AI Draft (promoted)",
}
