"""
Module: talos.burp

Purpose:
    Burp Suite integration: metadata headers on outbound attack requests
    so the Talos Burp extension can group traffic by engine → endpoint.
    Preferred path is localhost ingest (no X-Talos-* on the proxied
    request) because Burp HTTP history cannot be rewritten.

    Engines: Input Validation, Unauthenticated Execution, BAC,
    Auth-Session Testing, CORS Misconfiguration, Intruder.

Dependencies: talos.burp.config, headers, outbound, trace
Data flow:
    engine send → attach_burp_trace / prepare_send_headers
        → snapshot ~/.talos/burp/<project>.jsonl
        → httpx → upstream Burp → extension (bind + hydrate + strip)
Side effects: None at import time.
"""

from talos.burp.config import (
    BurpRuntimeConfig,
    burp_config_from_effective,
    ensure_process_burp_config,
    get_process_burp_config,
    load_burp_config_for_project,
    reset_process_burp_config,
    set_process_burp_config,
)
from talos.burp.headers import (
    HEADER_ANALYSIS,
    HEADER_DETAIL,
    HEADER_ENDPOINT,
    HEADER_ENDPOINT_ID,
    HEADER_ENGINE,
    HEADER_GROUP,
    HEADER_HOST,
    HEADER_LOCATION,
    HEADER_PARAM,
    HEADER_PAYLOAD_TYPE,
    HEADER_PROJECT,
    HEADER_PROJECT_NAME,
    HEADER_RECORD_ID,
    HEADER_TECHNIQUE,
    HEADER_VARIANT,
    SUFFIX_ANALYSIS,
    SUFFIX_DETAIL,
    SUFFIX_ENDPOINT,
    SUFFIX_ENDPOINT_ID,
    SUFFIX_ENGINE,
    SUFFIX_GROUP,
    SUFFIX_HOST,
    SUFFIX_LOCATION,
    SUFFIX_PARAM,
    SUFFIX_PAYLOAD_TYPE,
    SUFFIX_PROJECT,
    SUFFIX_PROJECT_NAME,
    SUFFIX_RECORD_ID,
    SUFFIX_TECHNIQUE,
    SUFFIX_VARIANT,
    apply_overlay,
    apply_trace_headers,
    build_headers,
    maybe_apply_burp_headers,
    sanitize_header_value,
    sanitize_prefix,
)
from talos.burp.outbound import prepare_send_headers
from talos.burp.snapshot import (
    SnapshotProject,
    list_projects,
    load_records,
    ensure_project_snapshot,
    backfill_findings_from_db,
    backfill_responses_from_db,
    record_finding,
    record_from_flow,
    record_http_response,
    record_request,
    record_send_failure,
    record_send_response,
    resolve_project_identity,
    snapshot_root,
)
from talos.burp.trace import (
    ENGINE_AUTH_SESSION,
    ENGINE_BAC,
    ENGINE_CORS,
    ENGINE_SQLI,
    ENGINE_PATH_TRAVERSAL,
    ENGINE_SMUGGLE,
    ENGINE_INPUT_VALIDATION,
    ENGINE_ERROR_INTEL,
    ENGINE_FINDINGS,
    ENGINE_INTRUDER,
    ENGINE_PASSIVE,
    ENGINE_UNAUTH,
    GROUP_ENDPOINTS,
    BurpTrace,
    attach_burp_trace,
    attach_iv_burp_trace,
    endpoint_label,
    normalize_host,
    trace_from_flow_meta,
)

__all__ = [
    "BurpRuntimeConfig",
    "BurpTrace",
    "ENGINE_AUTH_SESSION",
    "ENGINE_BAC",
    "ENGINE_CORS",
    "ENGINE_SQLI",
    "ENGINE_PATH_TRAVERSAL",
    "ENGINE_SMUGGLE",
    "ENGINE_INPUT_VALIDATION",
    "ENGINE_ERROR_INTEL",
    "ENGINE_FINDINGS",
    "ENGINE_INTRUDER",
    "ENGINE_PASSIVE",
    "ENGINE_UNAUTH",
    "GROUP_ENDPOINTS",
    "HEADER_ANALYSIS",
    "HEADER_DETAIL",
    "HEADER_ENDPOINT",
    "HEADER_ENDPOINT_ID",
    "HEADER_ENGINE",
    "HEADER_GROUP",
    "HEADER_HOST",
    "HEADER_LOCATION",
    "HEADER_PARAM",
    "HEADER_PAYLOAD_TYPE",
    "HEADER_PROJECT",
    "HEADER_PROJECT_NAME",
    "HEADER_RECORD_ID",
    "HEADER_TECHNIQUE",
    "HEADER_VARIANT",
    "SUFFIX_ANALYSIS",
    "SUFFIX_DETAIL",
    "SUFFIX_ENDPOINT",
    "SUFFIX_ENDPOINT_ID",
    "SUFFIX_ENGINE",
    "SUFFIX_GROUP",
    "SUFFIX_HOST",
    "SUFFIX_LOCATION",
    "SUFFIX_PARAM",
    "SUFFIX_PAYLOAD_TYPE",
    "SUFFIX_PROJECT",
    "SUFFIX_PROJECT_NAME",
    "SUFFIX_RECORD_ID",
    "SUFFIX_TECHNIQUE",
    "SUFFIX_VARIANT",
    "SnapshotProject",
    "apply_overlay",
    "apply_trace_headers",
    "attach_burp_trace",
    "attach_iv_burp_trace",
    "build_headers",
    "burp_config_from_effective",
    "endpoint_label",
    "ensure_process_burp_config",
    "ensure_project_snapshot",
    "get_process_burp_config",
    "list_projects",
    "load_burp_config_for_project",
    "load_records",
    "maybe_apply_burp_headers",
    "normalize_host",
    "prepare_send_headers",
    "backfill_findings_from_db",
    "backfill_responses_from_db",
    "record_finding",
    "record_from_flow",
    "record_http_response",
    "record_request",
    "record_send_failure",
    "record_send_response",
    "resolve_project_identity",
    "reset_process_burp_config",
    "sanitize_header_value",
    "sanitize_prefix",
    "set_process_burp_config",
    "snapshot_root",
    "trace_from_flow_meta",
]
