"""
Module: talos.url_sink.catalog

Purpose:
    Categorized parameter-name dictionaries for URL Sink Discovery.
    Replaces flat open_redirect / SSRF token lists with multi-category
    membership. Categories bias candidate *family* later; they do not
    alone invent a confirmed sink.

    Matching is case-insensitive after camelCase / snake / kebab normalization
    (see name_classify.normalize_param_name).

Categories:
    redirect          — open redirect / return / navigate surfaces
    webhook           — callback / hook / notify receivers
    remote_fetch      — generic URL/URI/endpoint/origin/fetch sinks
    remote_asset      — avatar / image / media / CDN asset URLs
    import_metadata   — feed / WSDL / schema / metadata import
    infrastructure    — backend / proxy / gateway / host / cluster
    network_probe     — healthcheck / probe / DNS / resolve
    path_like         — path / filepath / document / download
    oauth             — redirect_uri / return_uri style OAuth params

Dependencies: None (data only)
Data flow: imported by name_classify
Side effects: None.
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# Category constants (stable strings)
# ---------------------------------------------------------------------------

CATEGORY_REDIRECT = "redirect"
CATEGORY_WEBHOOK = "webhook"
CATEGORY_REMOTE_FETCH = "remote_fetch"
CATEGORY_REMOTE_ASSET = "remote_asset"
CATEGORY_IMPORT_METADATA = "import_metadata"
CATEGORY_INFRASTRUCTURE = "infrastructure"
CATEGORY_NETWORK_PROBE = "network_probe"
CATEGORY_PATH_LIKE = "path_like"
CATEGORY_OAUTH = "oauth"

ALL_CATEGORY_NAMES: tuple[str, ...] = (
    CATEGORY_REDIRECT,
    CATEGORY_WEBHOOK,
    CATEGORY_REMOTE_FETCH,
    CATEGORY_REMOTE_ASSET,
    CATEGORY_IMPORT_METADATA,
    CATEGORY_INFRASTRUCTURE,
    CATEGORY_NETWORK_PROBE,
    CATEGORY_PATH_LIKE,
    CATEGORY_OAUTH,
)

# ---------------------------------------------------------------------------
# Name sets (normalized form: lowercase, underscores, no hyphens)
# Keys are already normalized tokens; multi-word names use underscores.
# ---------------------------------------------------------------------------

# Primary category per token when only one is expected; multi-membership
# is expressed by listing the same token in multiple sets.
_REDIRECT_NAMES: frozenset[str] = frozenset({
    "redirect",
    "redirect_to",
    "redirectto",
    "redirect_url",
    "redirecturl",
    "redirect_uri",
    "redirecturi",
    "return",
    "return_to",
    "returnto",
    "return_url",
    "returnurl",
    "return_uri",
    "returnuri",
    "return_path",
    "returnpath",
    "goto",
    "go",
    "next",
    "continue",
    "continue_to",
    "continueto",
    "continue_url",
    "continueurl",
    "back",
    "back_to",
    "backto",
    "back_url",
    "backurl",
    "dest",
    "destination",
    "target",
    "forward",
    "forward_to",
    "forwardto",
    "relay",
    "relay_state",
    "relaystate",
    "cancel",
    "cancel_url",
    "cancelurl",
    "success",
    "success_url",
    "successurl",
    "failure",
    "failure_url",
    "failureurl",
    "exit",
    "exit_url",
    "exiturl",
    "finish",
    "finish_url",
    "finishurl",
    "complete",
    "post_login",
    "postlogin",
    "post_logout",
    "postlogout",
    "after",
    "after_login",
    "afterlogin",
    "after_logout",
    "afterlogout",
    "landing",
    "navigate",
    "jump",
    "from",
    "to",
    "view",
    "visit",
    "open",
    "screen",
    "page",
    "home",
    "homepage",
    "resume",
    "resume_url",
    "resumeurl",
    "redir",
    "rurl",
    "ref",
    "reference",
    "referer",
    "referrer",
})

_WEBHOOK_NAMES: frozenset[str] = frozenset({
    "callback",
    "callback_url",
    "callbackurl",
    "webhook",
    "webhook_url",
    "webhookurl",
    "hook",
    "hook_url",
    "hookurl",
    "notify",
    "notification",
    "listener",
    "receiver",
    "receiver_url",
    "receiverurl",
    "event_url",
    "eventurl",
    "ping",
    "push",
    "push_url",
    "pushurl",
    "cb",
})

_REMOTE_FETCH_NAMES: frozenset[str] = frozenset({
    "url",
    "uri",
    "href",
    "src",
    "source",
    "link",
    "fetch",
    "fetch_url",
    "fetchurl",
    "resource",
    "resource_url",
    "resourceurl",
    "endpoint",
    "origin",
    "api",
    "api_url",
    "apiurl",
    "base",
    "base_url",
    "baseurl",
    "base_uri",
    "baseuri",
    "import",
    "import_url",
    "importurl",
    "feed",
    "feed_url",
    "feedurl",
    "sync",
    "sync_url",
    "syncurl",
    "pull",
    "remote",
    "remote_url",
    "remoteurl",
    "external",
    "thirdparty",
    "third_party",
    "public_url",
    "publicurl",
    "content",
    "content_url",
    "contenturl",
    "object",
    "object_url",
    "objecturl",
    "blob",
    "blob_url",
    "bloburl",
    "location",
    "locator",
    "loc",
    "request",
    "query",
    "load",
    "include",
    "connect",
    "connection",
    "service",
    "service_url",
    "serviceurl",
    "integration",
    "integration_url",
    "integrationurl",
    "partner",
    "vendor",
    "controller",
    "dispatcher",
    "route",
    "router",
    "rpc",
    "grpc",
    "graphql",
    "socket",
    "ws",
    "stream",
    "stream_url",
    "streamurl",
    "delivery",
    "broker",
    "relay_url",  # distinct from redirect RelayState
    "upstream",
    "upstream_url",
    "upstreamurl",
    "proxy_url",
    "proxyurl",
    "gateway_url",
    "gatewayurl",
    "cdn",
    "cdn_url",
    "cdnurl",
    "static",
    "static_url",
    "staticurl",
    "asset",
    "asset_url",
    "asseturl",
    "canonical",
    "website",
    "site",
    "domain",
    "host",
    "hostname",
    "server",
    "instance",
    "node",
    "cluster",
    "pod",
    "zone",
    "region",
    "ip",
    "address",
    "prefix",
    "path",  # also path_like; multi-match
    "template",
    "manifest",
    "playlist",
    "m3u8",
    "mpd",
    "tracking",
    "tracking_url",
    "trackingurl",
    "unsubscribe",
    "invite",
    "magic",
    "signin",
    "signup",
    "login",
    "logout",
    "action",
    "activation",
    "status",
    "health",
    "config",
    "confirm",
    "confirmation",
    "validate",
    "verification",
    "verify",
    "check",
    "clone",
    "mirror",
    "migrate",
    "migration",
    "restore",
    "backup",
    "archive",
    "snapshot",
    "export",
    "export_url",
    "exporturl",
    "retrieve",
    "resolve",
    "resolver",
    "lookup",
    "browse",
    "portal",
    "federation",
    "module",
    "key",
    "metadata",
    "metadata_url",
    "metadataurl",
    "json",
    "json_url",
    "jsonurl",
    "xml",
    "xml_url",
    "xmlurl",
    "yaml",
    "schema",
    "schema_url",
    "schemaurl",
})

_REMOTE_ASSET_NAMES: frozenset[str] = frozenset({
    "avatar",
    "avatar_url",
    "avatarurl",
    "image",
    "image_url",
    "imageurl",
    "img",
    "img_url",
    "imgurl",
    "logo",
    "logo_url",
    "logourl",
    "banner",
    "photo",
    "photo_url",
    "photourl",
    "picture",
    "picture_url",
    "pictureurl",
    "thumb",
    "thumbnail",
    "thumb_url",
    "thumburl",
    "media",
    "media_url",
    "mediaurl",
    "favicon",
    "icon",
    "icon_url",
    "iconurl",
    "css",
    "style",
    "font",
    "font_url",
    "fonturl",
    "video",
    "video_url",
    "videourl",
    "audio",
    "audio_url",
    "audiourl",
    "cover",
    "background",
    "caption",
    "subtitle",
    "transcript",
    "attachment",
    "file",
    "filename",
    "filepath",
    "document",
    "pdf",
    "csv",
    "zip",
    "tar",
    "gz",
    "atom",
    "rss",
    "opml",
    "dtd",
    "wsdl",
    "xsd",
    "js",
    "script",
    "script_url",
    "scripturl",
})

_IMPORT_METADATA_NAMES: frozenset[str] = frozenset({
    "feed",
    "feed_url",
    "feedurl",
    "rss",
    "atom",
    "import",
    "import_url",
    "importurl",
    "wsdl",
    "xsd",
    "dtd",
    "opml",
    "swagger",
    "openapi",
    "metadata",
    "metadata_url",
    "metadataurl",
    "schema",
    "schema_url",
    "schemaurl",
    "manifest",
    "playlist",
})

_INFRASTRUCTURE_NAMES: frozenset[str] = frozenset({
    "backend",
    "backend_url",
    "backendurl",
    "proxy",
    "proxy_url",
    "proxyurl",
    "gateway",
    "gateway_url",
    "gatewayurl",
    "upstream",
    "upstream_url",
    "upstreamurl",
    "host",
    "hostname",
    "server",
    "cluster",
    "node",
    "pod",
    "container",
    "container_url",
    "containerurl",
    "bucket",
    "bucket_url",
    "bucketurl",
    "s3",
    "gcs",
    "azure",
    "storage",
    "storage_url",
    "storageurl",
    "cdn",
    "cdn_url",
    "cdnurl",
    "dns",
    "ip",
    "address",
    "internal",
    "broker",
    "dispatcher",
    "controller",
    "listener",
    "receiver",
    "relay",
    "federation",
    "zone",
    "region",
    "instance",
    "service",
    "service_url",
    "serviceurl",
})

_NETWORK_PROBE_NAMES: frozenset[str] = frozenset({
    "healthcheck",
    "health_check",
    "probe",
    "ping",
    "validate",
    "verify",
    "verification",
    "check",
    "lookup",
    "resolve",
    "resolver",
    "dns",
    "status",
})

_PATH_LIKE_NAMES: frozenset[str] = frozenset({
    "path",
    "filepath",
    "filename",
    "file",
    "document",
    "download",
    "download_url",
    "downloadurl",
    "upload",
    "upload_url",
    "uploadurl",
    "attachment",
    "prefix",
    "location",
    "locator",
    "loc",
    "template",
    "dir",
    "directory",
    "folder",
})

_OAUTH_NAMES: frozenset[str] = frozenset({
    "redirect_uri",
    "redirecturi",
    "redirect_url",
    "redirecturl",
    "return_uri",
    "returnuri",
    "return_url",
    "returnurl",
    "post_logout_redirect_uri",
    "postlogoutredirecturi",
    "client_uri",
    "clienturi",
    "logo_uri",
    "logouri",
    "policy_uri",
    "policyuri",
    "tos_uri",
    "tosuri",
    "jwks_uri",
    "jwksuri",
    "sector_identifier_uri",
    "sectoridentifieruri",
})

# Map category → frozenset of normalized names
NAME_CATEGORIES: dict[str, frozenset[str]] = {
    CATEGORY_REDIRECT: _REDIRECT_NAMES,
    CATEGORY_WEBHOOK: _WEBHOOK_NAMES,
    CATEGORY_REMOTE_FETCH: _REMOTE_FETCH_NAMES,
    CATEGORY_REMOTE_ASSET: _REMOTE_ASSET_NAMES,
    CATEGORY_IMPORT_METADATA: _IMPORT_METADATA_NAMES,
    CATEGORY_INFRASTRUCTURE: _INFRASTRUCTURE_NAMES,
    CATEGORY_NETWORK_PROBE: _NETWORK_PROBE_NAMES,
    CATEGORY_PATH_LIKE: _PATH_LIKE_NAMES,
    CATEGORY_OAUTH: _OAUTH_NAMES,
}

# Prefer this order when choosing a single primary category for multi-match.
_PRIMARY_PRIORITY: tuple[str, ...] = (
    CATEGORY_OAUTH,
    CATEGORY_WEBHOOK,
    CATEGORY_REDIRECT,
    CATEGORY_IMPORT_METADATA,
    CATEGORY_REMOTE_ASSET,
    CATEGORY_NETWORK_PROBE,
    CATEGORY_INFRASTRUCTURE,
    CATEGORY_PATH_LIKE,
    CATEGORY_REMOTE_FETCH,
)


def primary_category(categories: list[str] | tuple[str, ...]) -> str | None:
    """
    Purpose:
        Pick one primary category from a multi-match list using stable priority.
    Input:
        categories — matching category ids (any order).
    Output:
        Primary category string, or None if empty.
    Side effects: None.
    """
    if not categories:
        return None
    present = set(categories)
    for cat in _PRIMARY_PRIORITY:
        if cat in present:
            return cat
    return categories[0]
