"""
Module: talos.error_intel.detectors.infrastructure

Purpose:
    Stage D — infrastructure / proxy / CDN / ingress error pages.

    Cloudflare, AWS/Azure/GCP, Envoy, Kubernetes ingress, nginx/Apache
    default error templates.  Category: infrastructure (usually medium/low).

Dependencies: re; talos.error_intel.{constants, detectors.base, models}
Data flow: text → list[RawErrorMatch]
Side effects: None.
"""

from __future__ import annotations

import re
from typing import Mapping, Optional

from talos.error_intel.constants import (
    CATEGORY_INFRASTRUCTURE,
    CONFIDENCE_CONFIRMED_PATTERN,
    CONFIDENCE_HIGH,
    CONFIDENCE_MEDIUM,
    CONFIDENCE_WEAK,
    DETECTOR_FAMILY_INFRA,
    LANG_UNKNOWN,
)
from talos.error_intel.detectors.base import (
    DEFAULT_STAGE_MATCH_CAP,
    build_raw_error_match,
)
from talos.error_intel.models import RawErrorMatch

# (detector_id, pattern, server_tag, confidence)
_INFRA_RULES: tuple[tuple[str, re.Pattern[str], str, str], ...] = (
    (
        "infra_cloudflare",
        # Exclude bare CDN hostnames (cdnjs.cloudflare.com asset refs).
        re.compile(
            r"\bcf-ray\b|"
            r"Attention Required!|"
            r"Error code\s+\d{3,4}|"
            r"cloudflare-nginx|"
            r"cloudflare\.com/5|"
            r"(?<!cdnjs\.)(?<!cdn\.)\bcloudflare\b",
            re.I,
        ),
        "cloudflare",
        CONFIDENCE_HIGH,
    ),
    (
        "infra_aws",
        # Require error chrome — bare "Amazon S3" appears in success copy.
        re.compile(
            r"Generated by cloudfront|"
            r"<Code>AccessDenied</Code>|"
            r"<Code>NoSuchBucket</Code>|"
            r"<Code>AllAccessDisabled</Code>|"
            r"<Code>PermanentRedirect</Code>|"
            r"The request could not be satisfied|"
            r"X-Amz-Error|"
            r"AWS ALB|"
            r"ELB-HealthChecker|"
            r"Amazon S3.*(?:Access Denied|Error|Forbidden)|"
            r"(?:Access Denied|Forbidden).*Amazon S3|"
            r"<Error>\s*<Code>",
            re.I,
        ),
        "aws",
        CONFIDENCE_HIGH,
    ),
    (
        "infra_azure",
        re.compile(
            r"Azure App Service|"
            r"Microsoft-Azure|"
            r"Error 4\d{2} - (?:Web App|App Service)|"
            r"The resource you are looking for has been removed",
            re.I,
        ),
        "azure",
        CONFIDENCE_HIGH,
    ),
    (
        "infra_gcp",
        re.compile(
            r"Google Frontend|gws\b|Cloud Run error|"
            r"Error:\s*Page not found.*Google|"
            r"server:\s*Google Frontend",
            re.I,
        ),
        "gcp",
        CONFIDENCE_MEDIUM,
    ),
    (
        "infra_envoy",
        re.compile(
            r"upstream connect error or disconnect/reset before headers|"
            r"NR\s+no healthy upstream|"
            r"envoy(?:/|\s)|"
            r"UAEX|"
            r"\"response_code_details\":\"via_upstream\"",
            re.I,
        ),
        "envoy",
        CONFIDENCE_CONFIRMED_PATTERN,
    ),
    (
        "infra_k8s",
        re.compile(
            r"default backend\s*-\s*\d{3}|"
            r"nginx ingress controller|"
            r"no Route matched with those values|"
            r"upstream timed out|"
            r"openresty",
            re.I,
        ),
        "kubernetes",
        CONFIDENCE_HIGH,
    ),
    (
        "infra_nginx",
        re.compile(
            r"<center>nginx</center>|"
            r"nginx/[\d.]+|"
            r"<hr><center>nginx|"
            r"502 Bad Gateway.*nginx|"
            r"504 Gateway Time-out",
            re.I,
        ),
        "nginx",
        CONFIDENCE_MEDIUM,
    ),
    (
        "infra_apache",
        re.compile(
            r"Apache/[\d.]+|"
            r"<address>Apache|"
            r"Additionally, a \d{3} (?:Bad Gateway|Service Unavailable)|"
            r"Server:\s*Apache",
            re.I,
        ),
        "apache",
        CONFIDENCE_MEDIUM,
    ),
    (
        "infra_iis",
        re.compile(
            r"IIS/[\d.]+|"
            r"Microsoft-IIS|"
            r"HTTP Error \d{3}\.\d+|"
            r"Server Error in Application",
            re.I,
        ),
        "iis",
        CONFIDENCE_MEDIUM,
    ),
    (
        "infra_haproxy",
        re.compile(r"\bhaproxy\b|HAProxy Error|503 Service Unavailable.*haproxy", re.I),
        "haproxy",
        CONFIDENCE_MEDIUM,
    ),
)


class InfrastructureErrorDetector:
    """
    Purpose:
        Stage D — proxy/CDN/ingress/web-server error chrome.
    """

    def __init__(self, *, max_matches: int = DEFAULT_STAGE_MATCH_CAP) -> None:
        self._max = max(1, int(max_matches))

    def detect(
        self,
        text: str,
        *,
        status_code: Optional[int] = None,
        headers: Optional[Mapping[str, str]] = None,
        content_type: Optional[str] = None,
    ) -> list[RawErrorMatch]:
        del content_type
        if not text or not text.strip():
            # Headers alone can still indicate CDN
            return self._from_headers(headers)

        matches: list[RawErrorMatch] = []
        seen: set[str] = set()

        for detector_id, pattern, server, confidence in _INFRA_RULES:
            if server in seen:
                continue
            m = pattern.search(text)
            if not m:
                continue
            # Cloudflare: require real edge/error chrome — not CDN asset hosts
            # or a bare "cloudflare" mention on an unrelated 5xx body.
            if detector_id == "infra_cloudflare":
                if re.search(r"cdnjs\.cloudflare\.com|cdn\.cloudflare\.com", text, re.I):
                    # Pure asset-host mentions alone are not edge errors.
                    if not re.search(
                        r"\bcf-ray\b|Error code\s+\d{3,4}|cloudflare-nginx|"
                        r"Attention Required!|cloudflare\.com/5",
                        text,
                        re.I,
                    ):
                        continue
                elif not re.search(
                    r"\bcf-ray\b|Error code\s+\d{3,4}|cloudflare-nginx|"
                    r"Attention Required!|cloudflare\.com/5|"
                    r"cloudflare.*(?:error|blocked|ray)|"
                    r"(?:error|blocked).*(?<!cdnjs\.)(?<!cdn\.)cloudflare",
                    text,
                    re.I,
                ):
                    # 5xx + cloudflare still needs more than the bare product name
                    if not (
                        status_code
                        and 500 <= int(status_code) <= 599
                        and re.search(
                            r"cloudflare-nginx|cf-ray|Error code\s+\d{3,4}",
                            text,
                            re.I,
                        )
                    ):
                        continue
            seen.add(server)
            matches.append(
                build_raw_error_match(
                    detector_id=detector_id,
                    family=DETECTOR_FAMILY_INFRA,
                    text=text,
                    match_start=m.start(),
                    match_end=m.end(),
                    exception_type=None,
                    confidence=confidence,
                    category_hint=CATEGORY_INFRASTRUCTURE,
                    language=LANG_UNKNOWN,
                    metadata={
                        "server": server,
                        "technologies": [server],
                    },
                )
            )
            if len(matches) >= self._max:
                break

        # Merge header-only signals
        for hm in self._from_headers(headers):
            srv = (hm.metadata or {}).get("server")
            if srv and srv in seen:
                continue
            if srv:
                seen.add(str(srv))
            matches.append(hm)
            if len(matches) >= self._max:
                break

        return matches

    def _from_headers(
        self,
        headers: Optional[Mapping[str, str]],
    ) -> list[RawErrorMatch]:
        if not headers:
            return []
        # Normalize keys
        lower = {str(k).lower(): str(v) for k, v in headers.items() if k is not None}
        out: list[RawErrorMatch] = []
        server = lower.get("server", "")
        via = lower.get("via", "")
        cf_ray = lower.get("cf-ray") or lower.get("cf-ray".lower())
        if cf_ray or "cloudflare" in server.lower():
            out.append(
                build_raw_error_match(
                    detector_id="infra_cloudflare_header",
                    family=DETECTOR_FAMILY_INFRA,
                    text=server or f"cf-ray:{cf_ray}",
                    match_start=0,
                    match_end=min(40, len(server or "cf-ray")),
                    confidence=CONFIDENCE_MEDIUM,
                    category_hint=CATEGORY_INFRASTRUCTURE,
                    language=LANG_UNKNOWN,
                    metadata={"server": "cloudflare", "technologies": ["cloudflare"], "from_header": True},
                    raw_snippet=(server or f"cf-ray: {cf_ray}")[:200],
                )
            )
        if re.search(r"\bnginx\b", server, re.I):
            out.append(
                build_raw_error_match(
                    detector_id="infra_nginx_header",
                    family=DETECTOR_FAMILY_INFRA,
                    text=server,
                    match_start=0,
                    match_end=len(server),
                    confidence=CONFIDENCE_WEAK,
                    category_hint=CATEGORY_INFRASTRUCTURE,
                    language=LANG_UNKNOWN,
                    metadata={"server": "nginx", "technologies": ["nginx"], "from_header": True},
                    raw_snippet=server[:200],
                )
            )
        if re.search(r"envoy|istio", server + " " + via, re.I):
            out.append(
                build_raw_error_match(
                    detector_id="infra_envoy_header",
                    family=DETECTOR_FAMILY_INFRA,
                    text=server or via,
                    match_start=0,
                    match_end=min(80, len(server or via)),
                    confidence=CONFIDENCE_MEDIUM,
                    category_hint=CATEGORY_INFRASTRUCTURE,
                    language=LANG_UNKNOWN,
                    metadata={"server": "envoy", "technologies": ["envoy"], "from_header": True},
                    raw_snippet=(server or via)[:200],
                )
            )
        return out
