"""
Module: talos.projects.flow_cli

Purpose:
    Universal flow CLI — list, inspect, and export any stored flow regardless
    of which module generated it (proxy capture, Input Validation, BAC,
    manual replay, etc.).

    Every replay flow is self-describing via the flow_meta JSON column
    introduced in schema v27.  This CLI exposes that data.

    Commands:
        talos flow list                  — inventory of captured/replay flows
        talos flow show <flow_id>        — display full request/response + meta
        talos flow export <flow_id>      — write Markdown file to project exports/
        talos flow export --module iv    — export all IV flows
        talos flow export --param <uuid> — export all flows for a parameter UUID

Dependencies: argparse, json, sqlite3, sys, talos.projects.access
Data flow:
    CLI args → DB reads (flows + roles + flow_meta) → stdout or export file
Side effects:
    - Read-only DB access.
    - export command writes a Markdown file to <project_dir>/exports/.
    - Exits 1 on error.
"""
from talos.cli_output import (
    add_format_argument,
    cli_error,
    cli_json,
    cli_usage_error,
    cli_precondition_error,
    wants_json,
)

import argparse
import json
import sqlite3
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from talos.projects.access import resolve_role
from talos.projects.manager import ProjectManager


def _require_active(manager: ProjectManager):
    project = manager.active()
    if project is None:
        cli_precondition_error("No active project. Run 'talos project open <id>', or pass --project <id> / set TALOS_PROJECT.")
    return project


def run_flow_cli(manager: ProjectManager, argv: list[str]) -> None:
    """
    Purpose:
        Parse flow subcommand arguments and dispatch to handler.
    Input:
        manager — ProjectManager instance.
        argv    — argument list after 'flow'.
    Side effects:
        Dispatches to command handlers.  Exits 0 for --help, 1 for errors.
    """
    parser = argparse.ArgumentParser(
        prog="talos flow",
        description=(
            "Universal flow inspector.  Works for any stored flow regardless "
            "of source (proxy capture, IV, BAC, manual replay, etc.)."
        ),
    )
    sub = parser.add_subparsers(dest="flow_cmd", metavar="<command>")
    sub.required = True

    # ------------------------------------------------------------------
    # list
    # ------------------------------------------------------------------
    p_list = sub.add_parser(
        "list",
        help="List captured and replay flows (UUID, endpoint, method, status, role, source).",
    )
    p_list.add_argument(
        "--endpoint",
        default=None,
        metavar="ENDPOINT_ID",
        help="Filter by endpoint UUID.",
    )
    p_list.add_argument(
        "--status-code",
        default=None,
        type=int,
        metavar="CODE",
        help="Filter by HTTP status code (exact match).",
    )
    p_list.add_argument(
        "--role",
        default=None,
        metavar="NAME|UUID",
        help="Filter by role name or UUID (capture-time role).",
    )
    p_list.add_argument(
        "--source",
        default=None,
        metavar="SOURCE",
        help=(
            "Filter by flow source "
            "(proxy_capture | manual_replay | auto_replay | iv_scan)."
        ),
    )
    p_list.add_argument(
        "--limit",
        default=None,
        type=int,
        metavar="N",
        help="Return at most N flows (most recent first).",
    )
    add_format_argument(p_list)

    # ------------------------------------------------------------------
    # show
    # ------------------------------------------------------------------
    p_show = sub.add_parser("show", help="Display a replay flow (request + response + metadata).")
    p_show.add_argument("flow_id", help="UUID of the replay flow.")
    add_format_argument(p_show)

    # ------------------------------------------------------------------
    # export
    # ------------------------------------------------------------------
    p_export = sub.add_parser(
        "export",
        help="Export one or more replay flows to Markdown.",
    )
    scope_grp = p_export.add_mutually_exclusive_group()
    scope_grp.add_argument("flow_id", nargs="?", help="Single flow UUID to export.")
    scope_grp.add_argument(
        "--module",
        metavar="MODULE",
        help="Export all flows generated by a module (e.g. input_validation, bac).",
    )
    scope_grp.add_argument(
        "--parameter",
        metavar="PARAM_UUID",
        help="Export all IV flows for a parameter UUID.",
    )
    scope_grp.add_argument(
        "--endpoint",
        metavar="ENDPOINT_ID",
        help="Export all flows for an endpoint UUID.",
    )
    scope_grp.add_argument(
        "--flows",
        nargs="+",
        metavar="FLOW_ID",
        help="Export a list of flow UUIDs.",
    )

    args = parser.parse_args(argv)

    if args.flow_cmd == "list":
        project = _require_active(manager)
        cmd_flow_list(project, args)
    elif args.flow_cmd == "show":
        _cmd_show(manager, args)
    elif args.flow_cmd == "export":
        _cmd_export(manager, args)
    else:
        parser.print_help()
        sys.exit(1)


# ---------------------------------------------------------------------------
# Command handlers
# ---------------------------------------------------------------------------

def list_flows(
    db_path: Path,
    project_id: str,
    *,
    endpoint_id: Optional[str] = None,
    status_code: Optional[int] = None,
    role_id: Optional[str] = None,
    source: Optional[str] = None,
    limit: Optional[int] = None,
) -> list[dict]:
    """
    Purpose:
        Return stored flows for a project with optional discovery filters.
        Primary lookup path for flow UUIDs used by show, export, replay,
        auth-config, and debugging.

    Input:
        db_path      — Path to the project's talos.db.
        project_id   — Project identifier; scopes the query.
        endpoint_id  — optional exact match on flows.endpoint_id.
        status_code  — optional exact match on HTTP status_code.
        role_id      — optional exact match on capture-time role UUID.
        source       — optional exact match on flow source label.
        limit        — optional max rows (most recent first). Must be > 0
                       when provided.

    Output:
        List of dicts ordered by captured_at DESC, each containing:
            id, method, host, path, status_code, role_id, role_name,
            source, captured_at, endpoint_id.
        role_name is the roles.name join result, or empty string when the
        role row is missing.

    Side effects:
        Read-only DB access.  Returns [] when the DB file does not exist.

    Raises:
        ValueError when limit is set and is not a positive integer.
    """
    if limit is not None and limit <= 0:
        raise ValueError(f"limit must be a positive integer, got {limit}")

    if not db_path.exists():
        return []

    clauses = ["f.project_id = ?"]
    params: list = [project_id]

    if endpoint_id is not None:
        clauses.append("f.endpoint_id = ?")
        params.append(endpoint_id)
    if status_code is not None:
        clauses.append("f.status_code = ?")
        params.append(status_code)
    if role_id is not None:
        clauses.append("f.role_id = ?")
        params.append(role_id)
    if source is not None:
        clauses.append("f.source = ?")
        params.append(source)

    where = " AND ".join(clauses)
    sql = f"""
        SELECT f.id, f.method, f.host, f.path, f.status_code,
               f.role_id, COALESCE(r.name, '') AS role_name,
               f.source, f.captured_at, f.endpoint_id
        FROM flows f
        LEFT JOIN roles r ON r.id = f.role_id
        WHERE {where}
        ORDER BY f.captured_at DESC
    """
    if limit is not None:
        sql += " LIMIT ?"
        params.append(limit)

    with sqlite3.connect(str(db_path)) as conn:
        conn.row_factory = sqlite3.Row
        rows = conn.execute(sql, params).fetchall()
    return [dict(row) for row in rows]


def cmd_flow_list(project: object, args: argparse.Namespace) -> None:
    """
    Purpose:
        List stored flows for the active project so operators can discover
        flow UUIDs for show, export, replay, and auth-config.
    Input:
        project — active Project instance (db_path, id).
        args    — parsed filters: endpoint, status_code, role, source, limit.
    Side effects:
        Reads flows/roles from DB; prints a table to stdout.
        Exits 1 when --role does not resolve or --limit is invalid.
    """
    db_path = project.db_path  # type: ignore[attr-defined]
    project_id = project.id    # type: ignore[attr-defined]

    role_id: str | None = None
    if args.role:
        role = resolve_role(db_path, args.role)
        if role is None:
            cli_error(f"Role '{args.role}' not found.")
        role_id = role["id"]

    try:
        flows = list_flows(
            db_path,
            project_id,
            endpoint_id=args.endpoint,
            status_code=args.status_code,
            role_id=role_id,
            source=args.source,
            limit=args.limit,
        )
    except ValueError as exc:
        cli_error(str(exc))

    if wants_json(args):
        cli_json(flows)
        return

    if not flows:
        print(
            "No flows match the given filters."
            if _has_list_filters(args)
            else "No flows captured yet."
        )
        return

    # Endpoint column: host + path for multi-host readability.
    def _endpoint_label(row: dict) -> str:
        host = row.get("host") or ""
        path = row.get("path") or ""
        return f"{host}{path}"

    def _status_label(row: dict) -> str:
        code = row.get("status_code")
        return str(code) if code is not None else "-"

    def _role_label(row: dict) -> str:
        name = row.get("role_name") or ""
        return name if name else (row.get("role_id") or "-")

    uuid_w = max(len("UUID"), max(len(f["id"] or "") for f in flows))
    ep_w = max(len("Endpoint"), max(len(_endpoint_label(f)) for f in flows))
    method_w = max(len("Method"), max(len(f.get("method") or "") for f in flows))
    status_w = max(len("Status"), max(len(_status_label(f)) for f in flows))
    role_w = max(len("Role"), max(len(_role_label(f)) for f in flows))
    source_w = max(len("Source"), max(len(f.get("source") or "") for f in flows))
    created_w = max(len("Created"), max(len(f.get("captured_at") or "") for f in flows))

    header = (
        f"{'UUID':<{uuid_w}}  {'Endpoint':<{ep_w}}  {'Method':<{method_w}}  "
        f"{'Status':<{status_w}}  {'Role':<{role_w}}  "
        f"{'Source':<{source_w}}  {'Created':<{created_w}}"
    )
    print(header)
    print("-" * len(header))
    for f in flows:
        print(
            f"{f['id']:<{uuid_w}}  "
            f"{_endpoint_label(f):<{ep_w}}  "
            f"{(f.get('method') or ''):<{method_w}}  "
            f"{_status_label(f):<{status_w}}  "
            f"{_role_label(f):<{role_w}}  "
            f"{(f.get('source') or ''):<{source_w}}  "
            f"{(f.get('captured_at') or ''):<{created_w}}"
        )
    print(f"\n{len(flows)} flow(s).")


def _has_list_filters(args: argparse.Namespace) -> bool:
    """
    Purpose:
        Detect whether the operator passed any list filter so empty results
        can print a more accurate message.
    Input:
        args — parsed flow list namespace.
    Output:
        True when at least one filter is set.
    Side effects: None.
    """
    return bool(
        args.endpoint
        or args.status_code is not None
        or args.role
        or args.source
    )


def _cmd_show(manager: ProjectManager, args: argparse.Namespace) -> None:
    """
    Purpose:
        Display a single replay flow with full request, response, and metadata.
    Side effects: Reads DB; prints to stdout (table text or JSON).
    """
    project = _require_active(manager)
    flow_id = args.flow_id
    flow = _fetch_flow(project.db_path, flow_id)
    if flow is None:
        cli_error(f"Flow '{flow_id}' not found.")
    if wants_json(args):
        # Enrich with parsed meta/headers for automation while keeping raw fields.
        payload = dict(flow)
        payload["flow_meta_parsed"] = _parse_flow_meta(flow)
        payload["request_headers_parsed"] = _parse_json(flow.get("request_headers", "{}"))
        payload["response_headers_parsed"] = _parse_json(flow.get("response_headers", "{}"))
        cli_json(payload)
        return
    print(_render_flow_text(flow))


def _cmd_export(manager: ProjectManager, args: argparse.Namespace) -> None:
    """
    Purpose:
        Export one or more flows to a Markdown file in <project_dir>/exports/.
    Side effects: Reads DB; writes Markdown file.
    """
    project = _require_active(manager)
    db_path = project.db_path

    flow_ids: list[str] = []

    if getattr(args, "flow_id", None):
        flow_ids = [args.flow_id]
    elif getattr(args, "flows", None):
        flow_ids = args.flows
    elif getattr(args, "module", None):
        flow_ids = _fetch_flow_ids_by_module(db_path, args.module)
    elif getattr(args, "parameter", None):
        flow_ids = _fetch_flow_ids_by_param_uuid(db_path, args.parameter)
    elif getattr(args, "endpoint", None):
        flow_ids = _fetch_flow_ids_by_endpoint(db_path, args.endpoint)
    else:
        cli_usage_error("Specify a flow_id, --module, --parameter, --endpoint, or --flows.")

    if not flow_ids:
        print("No flows found matching the specified scope.")
        return

    lines: list[str] = [f"# Flow Export — {len(flow_ids)} flows", ""]
    for fid in flow_ids:
        flow = _fetch_flow(db_path, fid)
        if flow is None:
            lines.append(f"## Flow `{fid[:8]}…`")
            lines.append(f"*(not found)*")
            lines.append("")
            continue
        lines.append(_render_flow_markdown(flow))
        lines.append("")

    md_content = "\n".join(lines)
    export_dir = _get_export_dir(project)
    # Build a descriptive filename.
    if len(flow_ids) == 1:
        fname = f"flow_{flow_ids[0][:16]}.md"
    elif getattr(args, "module", None):
        fname = f"flows_{args.module}.md"
    elif getattr(args, "parameter", None):
        fname = f"flows_param_{args.parameter[:16]}.md"
    elif getattr(args, "endpoint", None):
        fname = f"flows_endpoint_{args.endpoint[:16]}.md"
    else:
        fname = f"flows_export_{datetime.now(timezone.utc).strftime('%Y%m%d_%H%M%S')}.md"

    out_path = export_dir / fname
    out_path.write_text(md_content, encoding="utf-8")
    print(f"Exported {len(flow_ids)} flow(s) to {out_path}")


# ---------------------------------------------------------------------------
# Rendering helpers
# ---------------------------------------------------------------------------

def _render_flow_text(flow: dict) -> str:
    """
    Purpose:
        Render a flow dict as a human-readable terminal string.
    Output:
        Multi-line string with request, response, and metadata sections.
    Side effects: None.
    """
    lines: list[str] = []
    flow_id = flow.get("id", "")
    method = flow.get("method", "")
    url = flow.get("url", "")
    status_code = flow.get("status_code")
    source = flow.get("source", "")
    replay_reason = flow.get("replay_reason", "")
    original_flow_id = flow.get("original_flow_id", "")
    replay_error = flow.get("replay_error", "")
    captured_at = flow.get("captured_at", "")
    endpoint_id = flow.get("endpoint_id", "")

    lines.append(f"Flow: {flow_id}")
    lines.append("=" * 70)
    lines.append(f"  Source       : {source}")
    lines.append(f"  Reason       : {replay_reason or '(none)'}")
    lines.append(f"  Time         : {captured_at}")
    lines.append(f"  Original     : {original_flow_id or '(none)'}")
    lines.append(f"  Endpoint     : {endpoint_id or '(none)'}")
    if replay_error:
        lines.append(f"  Error        : {replay_error}")
    lines.append("")

    # Flow metadata (generated_by, analysis, payload, etc.)
    meta = _parse_flow_meta(flow)
    if meta:
        lines.append("  Metadata:")
        for k, v in sorted(meta.items()):
            lines.append(f"    {k:<20} : {v}")
        lines.append("")

    # Request
    lines.append("  REQUEST")
    lines.append("  " + "-" * 60)
    lines.append(f"  {method} {url}")
    req_headers = _parse_json(flow.get("request_headers", "{}"))
    for k, v in req_headers.items():
        lines.append(f"  {k}: {v}")
    req_body = flow.get("request_body")
    if req_body:
        if isinstance(req_body, bytes):
            req_body = req_body.decode("utf-8", errors="replace")
        lines.append("")
        lines.append(f"  {req_body[:1024]}")
    lines.append("")

    # Response
    lines.append("  RESPONSE")
    lines.append("  " + "-" * 60)
    lines.append(f"  HTTP/1.1 {status_code or '(no response)'}")
    resp_headers = _parse_json(flow.get("response_headers", "{}"))
    for k, v in list(resp_headers.items())[:20]:
        lines.append(f"  {k}: {v}")
    resp_body = flow.get("response_body")
    if resp_body:
        if isinstance(resp_body, bytes):
            resp_body = resp_body.decode("utf-8", errors="replace")
        lines.append("")
        lines.append(f"  {resp_body[:2048]}")
    lines.append("")

    return "\n".join(lines)


def _render_flow_markdown(flow: dict) -> str:
    """
    Purpose:
        Render a flow dict as a Markdown section for export files.
    Output:
        Markdown string (no trailing newline).
    Side effects: None.
    """
    flow_id = flow.get("id", "")
    method = flow.get("method", "")
    url = flow.get("url", "")
    status_code = flow.get("status_code")
    source = flow.get("source", "")
    replay_reason = flow.get("replay_reason", "")
    original_flow_id = flow.get("original_flow_id", "")
    replay_error = flow.get("replay_error", "")
    captured_at = flow.get("captured_at", "")

    meta = _parse_flow_meta(flow)

    lines: list[str] = []
    lines.append(f"## Flow `{flow_id}`")
    lines.append("")
    lines.append(f"| Field | Value |")
    lines.append(f"|-------|-------|")
    lines.append(f"| Source | {source} |")
    lines.append(f"| Reason | {replay_reason or '—'} |")
    lines.append(f"| Time | {captured_at} |")
    lines.append(f"| Original Flow | `{original_flow_id or '—'}` |")
    lines.append(f"| HTTP Status | **{status_code or '—'}** |")
    if replay_error:
        lines.append(f"| Error | {replay_error} |")
    lines.append("")

    if meta:
        lines.append("### Metadata")
        lines.append("")
        lines.append("| Field | Value |")
        lines.append("|-------|-------|")
        for k, v in sorted(meta.items()):
            lines.append(f"| {k} | `{v}` |")
        lines.append("")

    # Request
    req_headers = _parse_json(flow.get("request_headers", "{}"))
    req_body = flow.get("request_body")
    if isinstance(req_body, bytes):
        req_body = req_body.decode("utf-8", errors="replace")
    req_body = (req_body or "")[:2048]

    lines.append("### Request")
    lines.append("")
    lines.append("```http")
    lines.append(f"{method} {url}")
    for k, v in req_headers.items():
        lines.append(f"{k}: {v}")
    if req_body:
        lines.append("")
        lines.append(req_body)
    lines.append("```")
    lines.append("")

    # Response
    resp_headers = _parse_json(flow.get("response_headers", "{}"))
    resp_body = flow.get("response_body")
    if isinstance(resp_body, bytes):
        resp_body = resp_body.decode("utf-8", errors="replace")
    resp_body = (resp_body or "")[:4096]

    lines.append("### Response")
    lines.append("")
    lines.append("```http")
    lines.append(f"HTTP/1.1 {status_code or '(none)'}")
    for k, v in list(resp_headers.items())[:30]:
        lines.append(f"{k}: {v}")
    if resp_body:
        lines.append("")
        lines.append(resp_body)
    lines.append("```")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# DB helpers
# ---------------------------------------------------------------------------

def _fetch_flow(db_path: Path, flow_id: str) -> dict | None:
    """
    Purpose:
        Fetch a single flow row including flow_meta.
        Also fetches replay_reason and original_flow_id for context.
    Side effects: Read-only DB access.
    """
    if not db_path.exists():
        return None
    with sqlite3.connect(str(db_path)) as conn:
        conn.row_factory = sqlite3.Row
        row = conn.execute(
            """
            SELECT id, method, url, host, path, query,
                   request_headers, request_cookies,
                   request_body, status_code,
                   response_headers, response_body, content_type,
                   endpoint_id, role_id, module_id, source,
                   original_flow_id, replay_error, replay_reason,
                   captured_at, response_end,
                   COALESCE(flow_meta, '{}') AS flow_meta
            FROM flows WHERE id = ?
            """,
            (flow_id,),
        ).fetchone()
    return dict(row) if row else None


def _fetch_flow_ids_by_module(db_path: Path, module_name: str) -> list[str]:
    """
    Purpose:
        Fetch flow IDs where flow_meta.generated_by matches module_name.
        Uses source=auto_replay (mechanism) and generated_by (subsystem).
    Side effects: Read-only DB access.
    """
    with sqlite3.connect(str(db_path)) as conn:
        rows = conn.execute(
            """
            SELECT id FROM flows
            WHERE source IN ('auto_replay', 'manual_replay')
              AND COALESCE(flow_meta, '{}') LIKE ?
            ORDER BY captured_at DESC
            """,
            (f'%"generated_by": "{module_name}"%',),
        ).fetchall()
    return [r[0] for r in rows]


def _fetch_flow_ids_by_param_uuid(db_path: Path, param_uuid: str) -> list[str]:
    """
    Purpose:
        Fetch flow IDs linked to a parameter UUID via iv_probe_results.
    Side effects: Read-only DB access.
    """
    with sqlite3.connect(str(db_path)) as conn:
        rows = conn.execute(
            "SELECT flow_id FROM iv_probe_results WHERE param_uuid = ? AND flow_id IS NOT NULL",
            (param_uuid,),
        ).fetchall()
    return [r[0] for r in rows]


def _fetch_flow_ids_by_endpoint(db_path: Path, endpoint_id: str) -> list[str]:
    """
    Purpose:
        Fetch all replay flow IDs for a given endpoint.
    Side effects: Read-only DB access.
    """
    with sqlite3.connect(str(db_path)) as conn:
        rows = conn.execute(
            """
            SELECT id FROM flows
            WHERE endpoint_id = ?
              AND source != 'proxy_capture'
            ORDER BY captured_at DESC
            """,
            (endpoint_id,),
        ).fetchall()
    return [r[0] for r in rows]


def _parse_flow_meta(flow: dict) -> dict:
    """Parse flow_meta JSON column; return empty dict on failure."""
    raw = flow.get("flow_meta") or "{}"
    try:
        return json.loads(raw) if isinstance(raw, str) else (raw or {})
    except (ValueError, TypeError):
        return {}


def _parse_json(value) -> dict:
    """Parse a JSON string to dict; return empty dict on failure."""
    if isinstance(value, dict):
        return value
    try:
        return json.loads(value or "{}")
    except (ValueError, TypeError):
        return {}


def _get_export_dir(project) -> Path:
    """Return (and create) the project's exports directory."""
    export_dir = Path(str(project.db_path).replace("talos.db", "")) / "exports"
    export_dir.mkdir(parents=True, exist_ok=True)
    return export_dir
