"""
Module: talos.projects.flow_cli

Purpose:
    Universal flow CLI — inspect and export any replay flow regardless of
    which module generated it (Input Validation, BAC, manual replay, etc.).

    Every replay flow is self-describing via the flow_meta JSON column
    introduced in schema v27.  This CLI exposes that data.

    Commands:
        talos flow show <flow_id>        — display full request/response + meta
        talos flow export <flow_id>      — write Markdown file to project exports/
        talos flow export --module iv    — export all IV flows
        talos flow export --param <uuid> — export all flows for a parameter UUID

Dependencies: argparse, json, sqlite3, sys
Data flow:
    CLI args → DB reads (flows + flow_meta) → stdout or export file
Side effects:
    - Read-only DB access.
    - export command writes a Markdown file to <project_dir>/exports/.
    - Exits 1 on error.
"""

import argparse
import json
import sqlite3
import sys
from datetime import datetime, timezone
from pathlib import Path

from talos.projects.manager import ProjectManager


def _require_active(manager: ProjectManager):
    project = manager.active()
    if project is None:
        print("Error: no active project. Run 'talos project open <id>' first.",
              file=sys.stderr)
        sys.exit(1)
    return project


def run_flow_cli(manager: ProjectManager, argv: list[str]) -> None:
    """
    Purpose:
        Parse flow subcommand arguments and dispatch to handler.
    Input:
        manager — ProjectManager instance.
        argv    — argument list after 'flow'.
    Side effects:
        Dispatches to command handlers.  Exits 0 for --help, 1 for errors.
    """
    parser = argparse.ArgumentParser(
        prog="talos flow",
        description=(
            "Universal flow inspector.  Works for any replay flow regardless "
            "of which module generated it (IV, BAC, manual replay, etc.)."
        ),
    )
    sub = parser.add_subparsers(dest="flow_cmd", metavar="<command>")
    sub.required = True

    # ------------------------------------------------------------------
    # show
    # ------------------------------------------------------------------
    p_show = sub.add_parser("show", help="Display a replay flow (request + response + metadata).")
    p_show.add_argument("flow_id", help="UUID of the replay flow.")

    # ------------------------------------------------------------------
    # export
    # ------------------------------------------------------------------
    p_export = sub.add_parser(
        "export",
        help="Export one or more replay flows to Markdown.",
    )
    scope_grp = p_export.add_mutually_exclusive_group()
    scope_grp.add_argument("flow_id", nargs="?", help="Single flow UUID to export.")
    scope_grp.add_argument(
        "--module",
        metavar="MODULE",
        help="Export all flows generated by a module (e.g. input_validation, bac).",
    )
    scope_grp.add_argument(
        "--parameter",
        metavar="PARAM_UUID",
        help="Export all IV flows for a parameter UUID.",
    )
    scope_grp.add_argument(
        "--endpoint",
        metavar="ENDPOINT_ID",
        help="Export all flows for an endpoint UUID.",
    )
    scope_grp.add_argument(
        "--flows",
        nargs="+",
        metavar="FLOW_ID",
        help="Export a list of flow UUIDs.",
    )

    args = parser.parse_args(argv)

    if args.flow_cmd == "show":
        _cmd_show(manager, args.flow_id)
    elif args.flow_cmd == "export":
        _cmd_export(manager, args)
    else:
        parser.print_help()
        sys.exit(1)


# ---------------------------------------------------------------------------
# Command handlers
# ---------------------------------------------------------------------------

def _cmd_show(manager: ProjectManager, flow_id: str) -> None:
    """
    Purpose:
        Display a single replay flow with full request, response, and metadata.
    Side effects: Reads DB; prints to stdout.
    """
    project = _require_active(manager)
    flow = _fetch_flow(project.db_path, flow_id)
    if flow is None:
        print(f"Flow '{flow_id}' not found.", file=sys.stderr)
        sys.exit(1)
    print(_render_flow_text(flow))


def _cmd_export(manager: ProjectManager, args: argparse.Namespace) -> None:
    """
    Purpose:
        Export one or more flows to a Markdown file in <project_dir>/exports/.
    Side effects: Reads DB; writes Markdown file.
    """
    project = _require_active(manager)
    db_path = project.db_path

    flow_ids: list[str] = []

    if getattr(args, "flow_id", None):
        flow_ids = [args.flow_id]
    elif getattr(args, "flows", None):
        flow_ids = args.flows
    elif getattr(args, "module", None):
        flow_ids = _fetch_flow_ids_by_module(db_path, args.module)
    elif getattr(args, "parameter", None):
        flow_ids = _fetch_flow_ids_by_param_uuid(db_path, args.parameter)
    elif getattr(args, "endpoint", None):
        flow_ids = _fetch_flow_ids_by_endpoint(db_path, args.endpoint)
    else:
        print("Error: specify a flow_id, --module, --parameter, --endpoint, or --flows.",
              file=sys.stderr)
        sys.exit(1)

    if not flow_ids:
        print("No flows found matching the specified scope.")
        return

    lines: list[str] = [f"# Flow Export — {len(flow_ids)} flows", ""]
    for fid in flow_ids:
        flow = _fetch_flow(db_path, fid)
        if flow is None:
            lines.append(f"## Flow `{fid[:8]}…`")
            lines.append(f"*(not found)*")
            lines.append("")
            continue
        lines.append(_render_flow_markdown(flow))
        lines.append("")

    md_content = "\n".join(lines)
    export_dir = _get_export_dir(project)
    # Build a descriptive filename.
    if len(flow_ids) == 1:
        fname = f"flow_{flow_ids[0][:16]}.md"
    elif getattr(args, "module", None):
        fname = f"flows_{args.module}.md"
    elif getattr(args, "parameter", None):
        fname = f"flows_param_{args.parameter[:16]}.md"
    elif getattr(args, "endpoint", None):
        fname = f"flows_endpoint_{args.endpoint[:16]}.md"
    else:
        fname = f"flows_export_{datetime.now(timezone.utc).strftime('%Y%m%d_%H%M%S')}.md"

    out_path = export_dir / fname
    out_path.write_text(md_content, encoding="utf-8")
    print(f"Exported {len(flow_ids)} flow(s) to {out_path}")


# ---------------------------------------------------------------------------
# Rendering helpers
# ---------------------------------------------------------------------------

def _render_flow_text(flow: dict) -> str:
    """
    Purpose:
        Render a flow dict as a human-readable terminal string.
    Output:
        Multi-line string with request, response, and metadata sections.
    Side effects: None.
    """
    lines: list[str] = []
    flow_id = flow.get("id", "")
    method = flow.get("method", "")
    url = flow.get("url", "")
    status_code = flow.get("status_code")
    source = flow.get("source", "")
    replay_reason = flow.get("replay_reason", "")
    original_flow_id = flow.get("original_flow_id", "")
    replay_error = flow.get("replay_error", "")
    captured_at = flow.get("captured_at", "")
    endpoint_id = flow.get("endpoint_id", "")

    lines.append(f"Flow: {flow_id}")
    lines.append("=" * 70)
    lines.append(f"  Source       : {source}")
    lines.append(f"  Reason       : {replay_reason or '(none)'}")
    lines.append(f"  Time         : {captured_at}")
    lines.append(f"  Original     : {original_flow_id or '(none)'}")
    lines.append(f"  Endpoint     : {endpoint_id or '(none)'}")
    if replay_error:
        lines.append(f"  Error        : {replay_error}")
    lines.append("")

    # Flow metadata (generated_by, analysis, payload, etc.)
    meta = _parse_flow_meta(flow)
    if meta:
        lines.append("  Metadata:")
        for k, v in sorted(meta.items()):
            lines.append(f"    {k:<20} : {v}")
        lines.append("")

    # Request
    lines.append("  REQUEST")
    lines.append("  " + "-" * 60)
    lines.append(f"  {method} {url}")
    req_headers = _parse_json(flow.get("request_headers", "{}"))
    for k, v in req_headers.items():
        lines.append(f"  {k}: {v}")
    req_body = flow.get("request_body")
    if req_body:
        if isinstance(req_body, bytes):
            req_body = req_body.decode("utf-8", errors="replace")
        lines.append("")
        lines.append(f"  {req_body[:1024]}")
    lines.append("")

    # Response
    lines.append("  RESPONSE")
    lines.append("  " + "-" * 60)
    lines.append(f"  HTTP/1.1 {status_code or '(no response)'}")
    resp_headers = _parse_json(flow.get("response_headers", "{}"))
    for k, v in list(resp_headers.items())[:20]:
        lines.append(f"  {k}: {v}")
    resp_body = flow.get("response_body")
    if resp_body:
        if isinstance(resp_body, bytes):
            resp_body = resp_body.decode("utf-8", errors="replace")
        lines.append("")
        lines.append(f"  {resp_body[:2048]}")
    lines.append("")

    return "\n".join(lines)


def _render_flow_markdown(flow: dict) -> str:
    """
    Purpose:
        Render a flow dict as a Markdown section for export files.
    Output:
        Markdown string (no trailing newline).
    Side effects: None.
    """
    flow_id = flow.get("id", "")
    method = flow.get("method", "")
    url = flow.get("url", "")
    status_code = flow.get("status_code")
    source = flow.get("source", "")
    replay_reason = flow.get("replay_reason", "")
    original_flow_id = flow.get("original_flow_id", "")
    replay_error = flow.get("replay_error", "")
    captured_at = flow.get("captured_at", "")

    meta = _parse_flow_meta(flow)

    lines: list[str] = []
    lines.append(f"## Flow `{flow_id}`")
    lines.append("")
    lines.append(f"| Field | Value |")
    lines.append(f"|-------|-------|")
    lines.append(f"| Source | {source} |")
    lines.append(f"| Reason | {replay_reason or '—'} |")
    lines.append(f"| Time | {captured_at} |")
    lines.append(f"| Original Flow | `{original_flow_id or '—'}` |")
    lines.append(f"| HTTP Status | **{status_code or '—'}** |")
    if replay_error:
        lines.append(f"| Error | {replay_error} |")
    lines.append("")

    if meta:
        lines.append("### Metadata")
        lines.append("")
        lines.append("| Field | Value |")
        lines.append("|-------|-------|")
        for k, v in sorted(meta.items()):
            lines.append(f"| {k} | `{v}` |")
        lines.append("")

    # Request
    req_headers = _parse_json(flow.get("request_headers", "{}"))
    req_body = flow.get("request_body")
    if isinstance(req_body, bytes):
        req_body = req_body.decode("utf-8", errors="replace")
    req_body = (req_body or "")[:2048]

    lines.append("### Request")
    lines.append("")
    lines.append("```http")
    lines.append(f"{method} {url}")
    for k, v in req_headers.items():
        lines.append(f"{k}: {v}")
    if req_body:
        lines.append("")
        lines.append(req_body)
    lines.append("```")
    lines.append("")

    # Response
    resp_headers = _parse_json(flow.get("response_headers", "{}"))
    resp_body = flow.get("response_body")
    if isinstance(resp_body, bytes):
        resp_body = resp_body.decode("utf-8", errors="replace")
    resp_body = (resp_body or "")[:4096]

    lines.append("### Response")
    lines.append("")
    lines.append("```http")
    lines.append(f"HTTP/1.1 {status_code or '(none)'}")
    for k, v in list(resp_headers.items())[:30]:
        lines.append(f"{k}: {v}")
    if resp_body:
        lines.append("")
        lines.append(resp_body)
    lines.append("```")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# DB helpers
# ---------------------------------------------------------------------------

def _fetch_flow(db_path: Path, flow_id: str) -> dict | None:
    """
    Purpose:
        Fetch a single flow row including flow_meta.
        Also fetches replay_reason and original_flow_id for context.
    Side effects: Read-only DB access.
    """
    if not db_path.exists():
        return None
    with sqlite3.connect(str(db_path)) as conn:
        conn.row_factory = sqlite3.Row
        row = conn.execute(
            """
            SELECT id, method, url, host, path, query,
                   request_headers, request_cookies,
                   request_body, status_code,
                   response_headers, response_body, content_type,
                   endpoint_id, role_id, module_id, source,
                   original_flow_id, replay_error, replay_reason,
                   captured_at, response_end,
                   COALESCE(flow_meta, '{}') AS flow_meta
            FROM flows WHERE id = ?
            """,
            (flow_id,),
        ).fetchone()
    return dict(row) if row else None


def _fetch_flow_ids_by_module(db_path: Path, module_name: str) -> list[str]:
    """
    Purpose:
        Fetch flow IDs where flow_meta.generated_by matches module_name.
        Uses source=auto_replay (mechanism) and generated_by (subsystem).
    Side effects: Read-only DB access.
    """
    with sqlite3.connect(str(db_path)) as conn:
        rows = conn.execute(
            """
            SELECT id FROM flows
            WHERE source IN ('auto_replay', 'manual_replay')
              AND COALESCE(flow_meta, '{}') LIKE ?
            ORDER BY captured_at DESC
            """,
            (f'%"generated_by": "{module_name}"%',),
        ).fetchall()
    return [r[0] for r in rows]


def _fetch_flow_ids_by_param_uuid(db_path: Path, param_uuid: str) -> list[str]:
    """
    Purpose:
        Fetch flow IDs linked to a parameter UUID via iv_probe_results.
    Side effects: Read-only DB access.
    """
    with sqlite3.connect(str(db_path)) as conn:
        rows = conn.execute(
            "SELECT flow_id FROM iv_probe_results WHERE param_uuid = ? AND flow_id IS NOT NULL",
            (param_uuid,),
        ).fetchall()
    return [r[0] for r in rows]


def _fetch_flow_ids_by_endpoint(db_path: Path, endpoint_id: str) -> list[str]:
    """
    Purpose:
        Fetch all replay flow IDs for a given endpoint.
    Side effects: Read-only DB access.
    """
    with sqlite3.connect(str(db_path)) as conn:
        rows = conn.execute(
            """
            SELECT id FROM flows
            WHERE endpoint_id = ?
              AND source != 'proxy_capture'
            ORDER BY captured_at DESC
            """,
            (endpoint_id,),
        ).fetchall()
    return [r[0] for r in rows]


def _parse_flow_meta(flow: dict) -> dict:
    """Parse flow_meta JSON column; return empty dict on failure."""
    raw = flow.get("flow_meta") or "{}"
    try:
        return json.loads(raw) if isinstance(raw, str) else (raw or {})
    except (ValueError, TypeError):
        return {}


def _parse_json(value) -> dict:
    """Parse a JSON string to dict; return empty dict on failure."""
    if isinstance(value, dict):
        return value
    try:
        return json.loads(value or "{}")
    except (ValueError, TypeError):
        return {}


def _get_export_dir(project) -> Path:
    """Return (and create) the project's exports directory."""
    export_dir = Path(str(project.db_path).replace("talos.db", "")) / "exports"
    export_dir.mkdir(parents=True, exist_ok=True)
    return export_dir
